services:
    #Spring Boot Application
    spring-boot-app:
      image: backend
      ports:
        - "0.0.0.0:8891:8891"
      environment:
        - SPRING DATASOURCE_URL=jdbc:mysql://mysql:3306/api etudiant
        - SPRING DATASOURCE_USERNAME=root
        - SPRING DATASOURCE_PASSWORD=root
        SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
        - SPRING JPA HIBERNATE DDL AUTO=update
      depends_on:
        - mysql
#MySQL Database
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'api etudiant'
      MYSQL_ROOT_USERNAME: 'root'
      MYSQL ROOT PASSWORD: 'root'
    ports:
      - '0.0.0.0:3306:3306'
    volumes:
      - api etudiant:/var/lib/mysql
  # liste des volumes
volumes:
  api etudiant:
